apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  labels:
    app: microservices
data:
  gateway_url: "http://gateway-svc:8000"
  customer_service_url: "http://customer-svc:8003"
  product_service_url: "http://product-svc:8002"
  shopping_service_url: "http://shopping-svc:8001"
