apiVersion: v1
kind: Namespace
metadata:
  name: databases
---
apiVersion: v1
kind: Namespace
metadata:
  name: message-broker
---
apiVersion: v1
kind: Namespace
metadata:
  name: services
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: services
data:
  host: mongodb-0.mongodb-svc.databases.svc.cluster.local:27017,mongodb-1.mongodb-svc.databases.svc.cluster.local:27017,mongodb-2.mongodb-svc.databases.svc.cluster.local:27017
---
apiVersion: v1
kind: Secret
metadata:
  name: services-secret
  namespace: services
type: Opaque
data:
  app_key: Z3JvdXAyX2h0dHBiX2FwcA==
