apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: services
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: services
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: hoanglonguit2003/nginx-ms:stable
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: PRODUCTS_URL
          value: http://products-svc:8000
        - name: CUSTOMER_URL
          value: http://customer-svc:8000
        - name: SHOPPING_URL
          value: http://shopping-svc:8000
