apiVersion: v1
kind: Service
metadata:
  name: customer-svc
  namespace: services
spec:
  selector:
    app: customer
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deploy
  namespace: services
  labels:
    app: customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: hoanglonguit2003/customer-ms:stable
        ports:
          - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: services-secret
              key: app_key
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: host
        - name: MONGODB_DATABASE
          value: shopping_ms_customer
        - name: MESSAGE_BROKER_HOST
          value: rabbitmq-0.rabbitmq-svc.message-broker.svc.cluster.local
        - name: MESSAGE_BROKER_PORT
          value: "5672"
