apiVersion: v1
kind: Service
metadata:
  name: mongoui-svc
  namespace: databases
spec:
  selector:
    app: mongoui
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
---
apiVersion: v1
kind: Pod
metadata:
  name: mongoui-pod
  namespace: databases
  labels:
    app: mongoui
spec:
  containers:
  - name: mongo-ui
    image: mongo-express
    ports:
      - containerPort: 8081
    env:
      - name: ME_CONFIG_MONGODB_URL
        value: mongodb://mongodb-0.mongodb-svc.databases.svc.cluster.local:27017,mongodb-1.mongodb-svc.databases.svc.cluster.local:27017,mongodb-2.mongodb-svc.databases.svc.cluster.local:27017
