apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ui-svc
  namespace: message-broker
spec:
  selector:
    app: rabbitmq
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 15672
    targetPort: 15672
