# Post Database
apiVersion: v1
kind: Service
metadata:
  name: customer-svc
spec:
  selector:
    app: customer
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      volumes:
        - name: customer-data
          persistentVolumeClaim:
            claimName: customer-pvc
      containers:
        - name: customer
          image: mongo:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.2"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
          volumeMounts:
            - name: customer-data
              mountPath: /data/customer
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  selector:
    app: product
  ports:
    - port: 27018
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      volumes:
        - name: product-data
          persistentVolumeClaim:
            claimName: product-pvc
      containers:
        - name: product
          image: mongo:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.2"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: product-data
              mountPath: /data/product

---
apiVersion: v1
kind: Service
metadata:
  name: shopping-svc
spec:
  selector:
    app: shopping
  ports:
    - port: 27019
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping
spec:
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      volumes:
        - name: shopping-data
          persistentVolumeClaim:
            claimName: shopping-pvc
      containers:
        - name: shopping
          image: mongo:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.2"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: shopping-data
              mountPath: /data/shopping
