apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
  hostPath:
    path: /data/mongodb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "512Mi"
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "512Mi"
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopping-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "512Mi"
  storageClassName: standard
