apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-service
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-service
  template:
    metadata:
      labels:
        app: queue-service
    spec:
      containers:
        - name: queue-service
          image: rabbitmq:3.12.8-management-alpine
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: rabbitmq-user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: rabbitmq-password
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
            requests:
              memory: 150Mi
              cpu: 100m
          ports:
            - name: queue
              containerPort: 5672
              protocol: TCP
            - name: mgmt
              containerPort: 15672
              protocol: TCP
          volumeMounts:
            - name: rabbittmq-local-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbittmq-local-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
