apiVersion: v1
kind: Service
metadata:
  name: queue-service
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: queue-service
  ports:
    - name: queue
      port: 5672
      targetPort: queue
      protocol: TCP
    - name: mgmt
      port: 15672
      targetPort: mgmt
      protocol: TCP
