apiVersion: v1
kind: Service
metadata:
  name: customer-svc
spec:
  selector:
    app: customer
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
spec:
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer-c
          image: hoanglonguit2203/customer:dev
          env:
            - name: PORT
              value: "8003"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: customer_uri
          resources:
            limits:
              memory: 128Mi
              cpu: "0.25"
          ports:
            - containerPort: 8003
