apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-c
          image: hoanglonguit2003/gateway-service:dev
          env:
            - name: PORT
              value: "8000"
            - name: CUSTOMER_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: customer_service_url
            - name: PRODUCT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: product_service_url
            - name: SHOPPING_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: shopping_service_url
          resources:
            limits:
              cpu: "0.25"
              memory: 128Mi
          ports:
            - containerPort: 8000
