apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  selector:
    app: product
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product-c
          image: hoanglonguit2003/product:dev
          env:
            - name: PORT
              value: "8002"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: product_uri
          resources:
            limits:
              memory: 128Mi
              cpu: "0.25"
          ports:
            - containerPort: 8002
