apiVersion: v1
kind: Service
metadata:
  name: shopping-svc
spec:
  selector:
    app: shopping
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-deployment
  labels:
    app: shopping
spec:
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping-c
          image: hoanglonguit2003/shopping:dev
          env:
            - name: PORT
              value: "8001"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: shopping_uri
          resources:
            limits:
              memory: 128Mi
              cpu: "0.25"
          ports:
            - containerPort: 8001
